config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
  get "/:message_id", to: "pages#home", as: :home_with_message, constraints: { message_id: /\d+/ }

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  resource :session
  resource :registration

  resources :accounts do
    collection do
      get "authenticate", to: "accounts#authenticate", as: :authenticate
      post "send/code", to: "accounts#send_code", as: :send_code
    end
  end

  resources :messages do
    get "select", to: "messages#select", as: :select, on: :collection
    post "select", to: "messages#select_create", as: :select_create, on: :collection
  end
  resources :spams do
    get "start", to: "spams#start", as: :start, on: :member
    get "status", to: "spams#status", as: :status, on: :member
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :spams
  has_one_attached :image

  validates_presence_of :caption
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: %i[show edit destroy]

  def index
    @messages = current_user.messages
  end

  def show
    @spam = Spam.new message_id: @message.id
  end

  def new
    @message = Message.new
  end

  def select
    @message = Message.new
  end

  def select_create
    @message = Message.new message_params do |msg|
      msg.user_id = current_user.id
    end

    if @message.save
      redirect_to start_spam_path(@message)
    else
      render :select, status: :unprocessable_entity
    end
  end

  def create
    @message = Message.new message_params do |msg|
      msg.user_id = current_user.id
    end

    if @message.save
      redirect_to messages_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @message.update message_params
      redirect_to @message
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @message.destroy
    redirect_to messages_path
  end

  private

  def set_message
    @message = current_user.messages.find params[:id]
  end

  def message_params
    params.require(:message).permit(:caption, :image)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<% method = message.new_record? ? :post : :patch %>
<% path = message.new_record? ? messages_path : message_path(message) %>
<%= simple_form_for message, url: (local_assigns[:force_path] || path), method: method do |f| %>
  <%= f.input :caption %>
  <%= f.input :image %>

  <%= f.button :button, "Submit" %>
<% end %>

app/views/messages/_message.html.erb
<div class="border rounded-xl p-4">

  <div class="flex justify-between items-center">
    <%= link_to start_spam_path(message), class: "flex items-center space-x-2" do %>
      <%= image_tag message.image.variant(resize_to_limit: [32, 32]) %>
      <div>
        <%= tag.p message.caption, class: "font-bold" %>
        <%= tag.p time_ago_in_words(message.created_at) %>
      </div>
    <% end %>
    <%= link_to message_path(message), class: "flex-none w-4 text-center", data: { turbo_confirm: "Are you sure?", turbo_method: :delete } do %>
      <i class="fa-solid fa-trash text-base text-rose-500"></i>
    <% end %>
  </div>

</div>

app/views/messages/edit.html.erb
<%= render "form" %>

app/views/messages/index.html.erb
<div class="space-y-6">
  <%= tag.p "Your Messages", class: "text-center text-base font-semibold" %>

  <% if @messages.any? %>
    <div class="my-3 text-center">
      <%= component "link", "add message", new_message_path %>
    </div>
    
    <div class="relative">
      <input type="text" class="w-full rounded-xl bg-indigo-100 py-4 px-3 pl-10 text-xs focus-visible:outline-none" placeholder="Search ...">
      <i class="absolute left-3 translate-y-[14px] text-xl text-black/30 fa-solid fa-magnifying-glass"></i>
    </div>

    <%= render @messages %>
  <% else %>
    <p class="text-center">You don't have any messages, <%= component "link", "add", new_message_path %> a new message</p>
  <% end %>
</div>

app/views/messages/new.html.erb
<%= render partial: "form", locals: { message: @message } %>

app/views/messages/select.html.erb
<div class="space-y-9">
  <p class="text-center font-bold text-sm">Message Select</p>

  <%= render partial: "messages/form", locals: { message: @message, force_path: select_create_messages_path } %>

  <% if current_user.messages.any? %>
    <%= render current_user.messages %>
  <% else %>
    <p class="text-center">You don't have any messages</p>
  <% end %>
</div>

app/views/messages/show.html.erb
<%= render @message %>

<%= render partial: "spams/form", locals: { spam: @spam } %>