config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
  get "/:message_id", to: "pages#home", as: :home_with_message, constraints: { message_id: /\d+/ }

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  resource :session
  resource :registration

  resources :accounts do
    collection do
      get "authenticate", to: "accounts#authenticate", as: :authenticate
      post "send/code", to: "accounts#send_code", as: :send_code
    end
  end

  resources :messages do
    get "select", to: "messages#select", as: :select, on: :collection
    post "select", to: "messages#select_create", as: :select_create, on: :collection
  end
  resources :spams do
    get "start", to: "spams#start", as: :start, on: :member
    get "status", to: "spams#status", as: :status, on: :member
  end
end

app/models/spam.rb
class Spam < ApplicationRecord
  has_many :spam_accounts, dependent: :destroy
  has_many :accounts, through: :spam_accounts
  belongs_to :user
  belongs_to :message

  validates_presence_of :message_id

  after_update_commit do
    broadcast_replace_to(
      :spams,
      target: "spam_#{id}_status",
      partial: "spams/status",
      locals: { spam: self }
    )

    if status == "completed"
      user.notify_success "Spam is completed successfully"
    end
  end
end

app/controllers/spams_controller.rb
class SpamsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_no_active_jobs, only: :create

  def start
    @spam = Spam.new
    @message = current_user.messages.find_by id: params[:id]
  end

  def status
    @spam = current_user.spams.find_by(id: params[:id])
  end

  def create
    @spam = Spam.new spam_params do |spam|
      spam.user_id = current_user.id
    end

    if @spam.save
      SpamJob.perform_later @spam
      redirect_to status_spam_path(@spam)
    else
    end
  end

  private

  def ensure_no_active_jobs
    if current_user.has_active_spam?
      current_user.notify_fail "You already have a spam job."

      head :forbidden
    end
  end

  def spam_params
    params.require(:spam).permit(:message_id)
  end
end

app/helpers/spams_helper.rb
module SpamsHelper
end

app/views/spams/_button.html.erb
<%= link_to select_messages_path, class: "w-32 h-32 ring-2 ring-indigo-500 rounded-full flex items-center justify-center" do %>
  <% tag.span "Enter Message", class: "font-semibold" %>
<% end %>

app/views/spams/_dropdown.html.erb
<div 
  data-dropdown-target="modal" 
  class="fixed inset-0 z-50 !m-0 bg-white hidden overflow-y-auto"
>
  <div class="px-4 pt-4 space-y-3">
    <div class="flex justify-end w-full">
      <!-- Close Button -->
      <button class="text-blue-500 underline text-center" data-action="click->dropdown#close">
        <i class="fa-solid fa-xmark text-2xl"></i>
      </button>
    </div>

    <!-- List Items -->
    <ul class="space-y-4">
      <% messages.each do |message| %>
        <li 
          class="flex items-center p-4 border rounded-lg cursor-pointer hover:bg-gray-100"
          data-action="click->dropdown#select"
          data-item-id="<%= message.id %>"
          data-item-text="<%= message.caption %>">
          <img src="<%= url_for(message.image) %>" alt="<%= message.caption %>" class="w-12 h-8 mr-4">
          <span class=""><%= message.caption %></span>
        </li>
      <% end %>
    </ul>

    <%= link_to "Write new Message", new_message_path, class: simple_form_button_class("block text-center") %>

    <!-- Hidden Input (Optional) -->
    <%= f.input :message_id, :as => :hidden, input_html: { data: { dropdown_target: "hiddenInput" } } %>
  </div>
</div>

app/views/spams/_form.html.erb
<%= simple_form_for spam, url: (local_assigns[:path] || spams_path) do |f| %>
  <%= f.input :message_id, :as => :hidden, input_html: { value: @message.id } %>
  <%= render partial: "spams/form_button" %>
<% end %>

app/views/spams/_form_button.html.erb
<% extra_classes = local_assigns[:started] ? "ring-amber-500" : "ring-indigo-500" %>
<%= button_tag class: "#{extra_classes} w-32 h-32 ring-2 rounded-full flex items-center justify-center mx-auto".strip do %>
  <% tag.span (local_assigns[:started] ? "Proceed" : "Start"), class: "font-semibold" %>
<% end %>

app/views/spams/_status.html.erb
<%= turbo_frame_tag "spam_#{spam.id}_status" do %>
  <div class="flex relative h-screen">
    <div class="absolute left-1/2 top-1/3 -translate-x-1/2">
      <%= tag.div class: "w-32 h-32 ring-2 #{spam.status == 'pending' ? 'ring-yellow-500' : 'ring-green-500'} rounded-full flex items-center justify-center" do %>
        <%= tag.span spam.status, class: "font-semibold" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/spams/start.html.erb
<%= tag.p @message.caption %>

app/views/spams/status.html.erb
<%= turbo_stream_from :spams %>
<%= render partial: "spams/status", locals: { spam: @spam } %>