config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"
  get "/:message_id", to: "pages#home", as: :home_with_message, constraints: { message_id: /\d+/ }

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  resource :session
  resource :registration

  resources :accounts do
    collection do
      get "authenticate", to: "accounts#authenticate", as: :authenticate
      post "send/code", to: "accounts#send_code", as: :send_code
    end
  end

  resources :messages do
    get "select", to: "messages#select", as: :select, on: :collection
    post "select", to: "messages#select_create", as: :select_create, on: :collection
  end
  resources :spams do
    get "start", to: "spams#start", as: :start, on: :member
    get "status", to: "spams#status", as: :status, on: :member
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar

  normalizes :phone, with: ->(phone) { (phone.to_i).abs.to_s }

  after_save :generate_avatar, if: -> { full_name_changed? }

  def full_name
    "Richard Morozko"
  end

  def generate_avatar
    return unless full_name.present?

    tempfile = AvatarGenerator.generate(full_name)
    avatar.attach(
      io: tempfile,
      filename: "#{id}-avatar.png",
      content_type: "image/png"
    )
    tempfile.close
    tempfile.unlink
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  require "httparty"

  before_action :authenticate_user!
  before_action :set_account, only: %i[show destroy]

  def index
  end

  def show
  end

  def new
    # renders a phone inout form
    @code_request = CodeRequest.new
  end

  def send_code
    @code_request = CodeRequest.new request_code_params do |record|
      record.user_id = current_user.id
    end

    sleep 1 # TODO delete this
    if @code_request.save
      request_body = body_with_credentials({
        phone_number: @code_request.phone
      })

      response = HTTParty.post(
        url + "/send/code",
        headers: { "Content-Type" => "application/json" },
        body: request_body.to_json
      )

      json_response = JSON.parse response.body

      if response.success?
        session[:phone_code_hash] = json_response["phone_code_hash"]
        session[:phone_number] = @code_request.phone
        session[:session_string] = json_response["session"]
        redirect_to authenticate_accounts_path
      else
        @code_request = CodeRequest.new

        case json_response["error"]
        when "phone_invalid"
          @code_request.errors.add(:phone, "phone number not valid")
        else
          @code_request.errors.add(:phone, "unexpected error")
        end

        render :new, status: :unprocessable_entity
      end
    else
      # is invalid
      render :new, status: :unprocessable_entity
    end
  end

  def authenticate
    # renders a code inout form
    @code_attempt = CodeAttempt.new
  end

  def create
    request_body = body_with_credentials({
      phone_number: session[:phone_number],
      phone_code_hash: session[:phone_code_hash],
      code: attempt_code_params[:code],
      session: session[:session_string]
    })

    response = HTTParty.post(
      url + "/verify/code",
      headers: { "Content-Type" => "application/json" },
      body: request_body.to_json
    )

    json_response = JSON.parse response.body

    if response.success?
      Account.create(user_id: current_user.id,
        phone: request_body[:phone_number],
        session_data: json_response["session"]
      )
      redirect_to accounts_path
    else
      @code_attempt = CodeAttempt.new

      case json_response["error"]
      when "code_invalid"
        @code_attempt.errors.add(:code, "code is not valid")
      else
        @code_attempt.errors.add(:code, "unexpected error")
      end

      render :authenticate, status: :unprocessable_entity
    end
  end

  def destroy
    if @account.present?
      @account.destroy
      redirect_to accounts_path
    else
      redirect_to accounts_path
    end
  end

  private

  def body_with_credentials(extra_hash)
    {
      app_id: Rails.application.credentials.telegram.app_id,
      api_hash: Rails.application.credentials.telegram.api_hash
    }.merge extra_hash
  end

  def url
    "http://localhost:5000"
  end

  def request_code_params
    params.require(:code_request).permit(:phone)
  end

  def attempt_code_params
    params.require(:code_attempt).permit(:code)
  end

  def set_account
    @account = Account.find params[:id]
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<%= tag.p account.phone, class: "text-center text-red-400" %>

app/views/accounts/_form.html.erb
<%= simple_form_for code_attempt, url: accounts_path do |f| %>

  <%= f.input :code, placeholder: "Enter code" %>
  <%= f.button :submit, "Submit" %>

<% end %>

app/views/accounts/_request_code_form.html.erb
<%= simple_form_for code_request, url: send_code_accounts_path, data: { controller: "spinner", action: "turbo:submit-start->spinner#replaceText turbo:submit-end->spinner#restoreText" } do |f| %>

  <%= f.input :phone, placeholder: "Enter phone" %>
  <%= f.button :button, "Submit", data: { spinner_target: "button" } %>

<% end %>

app/views/accounts/authenticate.html.erb
<div class="mt-6">

  <div class="space-y-12">
    <div class="space-y-3">
      <p class="text-base font-semibold text-center">Requested Code</p>
      <p class="text-xs text-center">Phone code for authenticate your Telegram Account</p>
    </div>
    <%= render partial: "form", locals: { code_attempt: @code_attempt } %>
    <p class="text-center">Please read our <%= component "link", "instructions", "#" %></p>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="space-y-6">
  <%= tag.p "Your Accounts", class: "text-center text-base font-semibold" %>

  <% if current_user.accounts.any? %>
    <div class="my-3 text-center">
      <%= component "link", "add account", new_account_path %>
    </div>
    
    <div class="relative">
      <input type="text" class="w-full rounded-xl bg-indigo-100 py-4 px-3 pl-10 text-xs focus-visible:outline-none" placeholder="Search ...">
      <i class="absolute left-3 translate-y-[14px] text-xl text-black/30 fa-solid fa-magnifying-glass"></i>
    </div>

    <% current_user.accounts.each do |account| %>
      <div class="border rounded-xl p-4">

        <!-- head -->
        <div class="flex justify-between items-center">
          <%= link_to account_path(account), class: "flex items-center space-x-2" do %>
            <%= tag.div "", class: 'flex-none w-8 h-8 rounded-full bg-indigo-100' %>
            <div>
              <%= tag.p account.full_name, class: "font-bold" %>
              <%= tag.p account.phone %>
            </div>
          <% end %>
          <%= link_to account_path(account), class: "flex-none w-4 text-center", data: { turbo_confirm: "Are you sure?", turbo_method: :delete } do %>
            <i class="fa-solid fa-trash text-base text-rose-500"></i>
          <% end %>
        </div>

      </div>
    <% end %>
  <% else %>
    <p class="text-center">You don't have any accounts, <%= component "link", "add", new_account_path %> a new account</p>
  <% end %>
</div>

app/views/accounts/new.html.erb
<div class="mt-6">

  <div class="space-y-12">
    <div class="space-y-3">
      <p class="text-base font-semibold text-center">Account's phone</p>
      <p class="text-xs text-center">Phone number who references to Telegram Account</p>
    </div>
    <%= render partial: "request_code_form", locals: { code_request: @code_request } %>
    <p class="text-center">Please read our <%= component "link", "instructions", "#" %></p>
  </div>
</div>

app/views/accounts/show.html.erb
<%= render @account %>